---

name: CI

# Controls when the workflow will run
on: # yamllint disable-line
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Run every day at midnight
  schedule:
    - cron: "0 0 * * *"

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      - name: Prepare OS for script
        run: |
          sudo mv ~/.bash_profile ~/.bash_profile.local
          sudo cp -r bash/.bash ~
          sudo cp bash/.bashrc ~
          sudo cp bash/.bash_profile ~
          sudo rm -rf /usr/local/n
          export me="$(whoami)"
          sudo chown -R "$me" ~
          sudo chmod -R 777 ~
          source ~/.bash_profile

      - name: Run install script
        run: bash scripts/install.sh

      - name: Stow linter configs
        run: stow vim

      - name: Run quality checks
        run: bash test.sh

  build-mac:
    runs-on: macos-11
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      - name: Run install script (skip OS stuff)
        run: |
          cp -r bash/ ~
          SKIP_OS_UPDATE=true bash scripts/install.sh

      - name: Stow linter configs
        run: stow vim

      - name: Run quality checks
        run: bash test.sh
