---

name: CI

# Controls when the workflow will run
on: # yamllint disable-line
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Run every day at midnight
  schedule:
    - cron: "0 0 * * *"

env:
  NODE_LLAMA_CPP_SKIP_DOWNLOAD: "true"

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Prepare OS for script
        run: |
          sudo mv ~/.bash_profile ~/.bash_profile.local
          sudo cp -r bash/.bash ~
          sudo cp bash/.bashrc ~
          sudo cp bash/.bash_profile ~
          sudo cp bash/.dir_colors ~
          cp mise/.tool-versions ~/
          export me="$(whoami)"
          sudo chown -R "$me" ~
          sudo chmod -R 777 ~
          source ~/.bash_profile

      - name: Run install script
        env:
          DOTFILES_DIR: ${{ github.workspace }}
        run: bash scripts/install.sh

      - name: Stow linter configs
        run: stow vim

      - name: Run quality checks
        run: bash test.sh

  build-redhat:
    runs-on: ubuntu-latest
    container:
      image: rockylinux:9
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SHELL: /bin/bash
    steps:
      - name: Install prerequisites
        run: yum install -y sudo git glibc-langpack-en xz

      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Prepare OS for script
        run: |
          cp -r bash/.bash ~
          cp bash/.bashrc ~
          cp bash/.bash_profile ~
          cp bash/.dir_colors ~
          cp mise/.tool-versions ~/
          mkdir -p ~/.local/bin
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Run install script
        env:
          DOTFILES_DIR: ${{ github.workspace }}
        run: bash scripts/install.sh

      - name: Stow linter configs
        run: stow vim

      - name: Run quality checks
        run: |
          ln -sf ~/.tool-versions .tool-versions
          bash test.sh

  build-mac:
    runs-on: macos-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Run install script (skip OS stuff)
        env:
          DOTFILES_DIR: ${{ github.workspace }}
          SKIP_OS_UPDATE: "true"
        run: |
          cp -r bash/ ~
          cp mise/.tool-versions ~/
          bash scripts/install.sh

      - name: Stow linter configs
        run: stow vim

      - name: Run quality checks
        run: bash test.sh
